// src/components/calculators/pilot2/CourseToSteerCalc.tsx
import { useState } from 'react';
import { Compass } from 'lucide-react';
import { NumberInput } from '../../shared/NumberInput';
import { courseToSteer } from '../../../utils/currentVector';

export interface CourseToSteerResult {
  requiredCMG: number; requiredSMG: number;
  setDir: number; driftSpeed: number;
  shipCourse: number; shipSpeed: number;
}

export const CourseToSteerCalc = ({ onResult }: { onResult: (r: CourseToSteerResult) => void }) => {
  const [requiredCMG, setRequiredCMG] = useState(90);
  const [requiredSMG, setRequiredSMG] = useState(12);
  const [setDir, setSetDir] = useState(180);
  const [driftSpeed, setDriftSpeed] = useState(2);

  const handleCalculate = () => {
    const r = courseToSteer(requiredCMG, requiredSMG, setDir, driftSpeed);
    onResult({ requiredCMG, requiredSMG, setDir, driftSpeed, shipCourse: r.shipCourse, shipSpeed: r.shipSpeed });
  };

  return (
    <div className="space-y-8 pb-20">
      <header>
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white border-l-4 border-cyan-600 pl-3">視針路・対水速力</h2>
        <p className="text-xs text-slate-400 mt-1 pl-4">目標CMG/SMGと潮流から視針路と対水速力を計算</p>
      </header>
      <section className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-4 transition-colors">
        <div className="text-sm font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-2">目標 (Required)</div>
        <div className="grid grid-cols-2 gap-4">
          <NumberInput label="目標CMG" value={requiredCMG} onChange={setRequiredCMG} unit="°" step={0.1} />
          <NumberInput label="目標SMG" value={requiredSMG} onChange={setRequiredSMG} unit="kn" step={0.1} />
        </div>
      </section>
      <section className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-4 transition-colors">
        <div className="text-sm font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-2">潮流 (Current)</div>
        <div className="grid grid-cols-2 gap-4">
          <NumberInput label="流向 (Set)" value={setDir} onChange={setSetDir} unit="°" step={0.1} />
          <NumberInput label="流速 (Drift)" value={driftSpeed} onChange={setDriftSpeed} unit="kn" step={0.1} />
        </div>
      </section>
      <button onClick={handleCalculate} className="w-full py-4 bg-gradient-to-r from-cyan-600 to-cyan-700 hover:from-cyan-500 hover:to-cyan-600 text-white font-bold rounded-xl shadow-lg hover:shadow-xl transition-all duration-200 flex justify-center items-center gap-2">
        <Compass size={20} /> 計算実行 (CALC)
      </button>
    </div>
  );
};

// src/lib/components/calculators/exam/nav/CourseToSteerCalc.svelte
<script lang="ts">
  import { calculateCourseToSteer } from '$lib/utils/examNavigation';

  let { onResult }: { onResult: (r: any) => void } = $props();

  let desiredTrack = $state(180);
  let shipSpeed = $state(15);
  let currentSet = $state(270);
  let currentDrift = $state(2);
  
  let result: any = $state(null);

  function handleCalculate() {
    const courseResult = calculateCourseToSteer(desiredTrack, shipSpeed, currentSet, currentDrift);

    const calcResult = {
      ...courseResult,
      desiredTrack,
      shipSpeed,
      currentSet,
      currentDrift
    };

    result = calcResult;
    onResult(calcResult);
  }
</script>

<div class="space-y-6 p-6">
  <div class="border-2 border-green-300 dark:border-green-700 rounded-lg p-4 bg-green-50 dark:bg-green-900/20">
    <h3 class="text-lg font-bold text-green-900 dark:text-green-100 mb-4">進行軸計算 (Course to Steer)</h3>
    
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">目標進路 (Desired Track) [°T]</label>
        <input
          type="number"
          bind:value={desiredTrack}
          step="1"
          min="0"
          max="360"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">船速 (Speed) [kt]</label>
        <input
          type="number"
          bind:value={shipSpeed}
          step="0.1"
          min="0"
          max="50"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">流向 (Current Set) [°T]</label>
        <input
          type="number"
          bind:value={currentSet}
          step="1"
          min="0"
          max="360"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">流速 (Current Drift) [kt]</label>
        <input
          type="number"
          bind:value={currentDrift}
          step="0.1"
          min="0"
          max="10"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
    </div>
  </div>

  <button
    onclick={handleCalculate}
    class="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 text-white font-bold py-3 rounded-lg transition-all transform hover:scale-105"
  >
    計算 (Calculate)
  </button>

  {#if result}
    <div class="border-t-2 border-slate-300 dark:border-slate-700 pt-6 mt-6 space-y-3 animate-in fade-in">
      <div class="bg-green-50 dark:bg-green-900/20 p-4 rounded-lg">
        <p class="text-sm text-slate-600 dark:text-slate-400">進行軸</p>
        <p class="text-3xl font-bold text-green-700 dark:text-green-400">
          {result.courseToSteer.toFixed(1)}°
        </p>
      </div>

      <div class="bg-emerald-50 dark:bg-emerald-900/20 p-4 rounded-lg">
        <p class="text-sm text-slate-600 dark:text-slate-400">対地速力</p>
        <p class="text-2xl font-bold text-emerald-700 dark:text-emerald-400">
          {result.groundSpeed.toFixed(1)} kt
        </p>
      </div>
    </div>
  {/if}
</div>
