// src/components/calculators/pilot2/TrueWindCalc.tsx
import { useState } from 'react';
import { Wind } from 'lucide-react';
import { NumberInput } from '../../shared/NumberInput';
import { trueWind } from '../../../utils/wind';

export interface TrueWindResult {
  relativeDir: number; relativeSpeed: number;
  shipCourse: number; shipSpeed: number;
  trueDir: number; trueSpeed: number;
}

export const TrueWindCalc = ({ onResult }: { onResult: (r: TrueWindResult) => void }) => {
  const [relativeDir, setRelativeDir] = useState(45);
  const [relativeSpeed, setRelativeSpeed] = useState(15);
  const [shipCourse, setShipCourse] = useState(0);
  const [shipSpeed, setShipSpeed] = useState(12);

  const handleCalculate = () => {
    const r = trueWind(relativeDir, relativeSpeed, shipCourse, shipSpeed);
    onResult({ relativeDir, relativeSpeed, shipCourse, shipSpeed, trueDir: r.trueDir, trueSpeed: r.trueSpeed });
  };

  return (
    <div className="space-y-8 pb-20">
      <header>
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white border-l-4 border-cyan-600 pl-3">真風向・風速</h2>
        <p className="text-xs text-slate-400 mt-1 pl-4">相対風向・風速と船速から真風向・真風速を計算</p>
      </header>
      <section className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-4 transition-colors">
        <div className="text-sm font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-2">相対風 (Apparent Wind)</div>
        <div className="grid grid-cols-2 gap-4">
          <NumberInput label="相対風向 (船首基準)" value={relativeDir} onChange={setRelativeDir} unit="°" step={1} />
          <NumberInput label="相対風速" value={relativeSpeed} onChange={setRelativeSpeed} unit="kn" step={0.1} />
        </div>
      </section>
      <section className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-4 transition-colors">
        <div className="text-sm font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider mb-2">船の状態</div>
        <div className="grid grid-cols-2 gap-4">
          <NumberInput label="船首方向 (Course)" value={shipCourse} onChange={setShipCourse} unit="°" step={0.1} />
          <NumberInput label="船速 (Speed)" value={shipSpeed} onChange={setShipSpeed} unit="kn" step={0.1} />
        </div>
      </section>
      <button onClick={handleCalculate} className="w-full py-4 bg-gradient-to-r from-cyan-600 to-cyan-700 hover:from-cyan-500 hover:to-cyan-600 text-white font-bold rounded-xl shadow-lg hover:shadow-xl transition-all duration-200 flex justify-center items-center gap-2">
        <Wind size={20} /> 計算実行 (CALC)
      </button>
    </div>
  );
};

// src/lib/components/calculators/exam/nav/TrueWindCalc.svelte
<script lang="ts">
  import { calculateTrueWind, calculateApparentWind } from '$lib/utils/examNavigation';

  let { onResult }: { onResult: (r: any) => void } = $props();

  let shipHeading = $state(180);
  let shipSpeed = $state(15);
  let apparentWindDir = $state(45);
  let apparentWindSpeed = $state(12);
  
  let result: any = $state(null);

  function handleCalculate() {
    const trueWind = calculateTrueWind(shipHeading, shipSpeed, apparentWindDir, apparentWindSpeed);

    const calcResult = {
      ...trueWind,
      shipHeading,
      shipSpeed,
      apparentWindDir,
      apparentWindSpeed
    };

    result = calcResult;
    onResult(calcResult);
  }
</script>

<div class="space-y-6 p-6">
  <div class="border-2 border-orange-300 dark:border-orange-700 rounded-lg p-4 bg-orange-50 dark:bg-orange-900/20">
    <h3 class="text-lg font-bold text-orange-900 dark:text-orange-100 mb-4">真風計算 (True Wind Calculation)</h3>
    
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">船の方位 (Heading) [°T]</label>
        <input
          type="number"
          bind:value={shipHeading}
          step="1"
          min="0"
          max="360"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">船速 (Speed) [kt]</label>
        <input
          type="number"
          bind:value={shipSpeed}
          step="0.1"
          min="0"
          max="50"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">見掛風向 (App. Wind Dir) [°]</label>
        <input
          type="number"
          bind:value={apparentWindDir}
          step="1"
          min="0"
          max="360"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
      <div>
        <label class="text-sm font-bold text-slate-700 dark:text-slate-300">見掛風速 (App. Wind Spd) [kt]</label>
        <input
          type="number"
          bind:value={apparentWindSpeed}
          step="0.1"
          min="0"
          max="50"
          class="w-full mt-1 px-3 py-2 border border-slate-300 dark:border-slate-600 rounded bg-white dark:bg-slate-800"
        />
      </div>
    </div>
  </div>

  <button
    onclick={handleCalculate}
    class="w-full bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-700 hover:to-red-700 text-white font-bold py-3 rounded-lg transition-all transform hover:scale-105"
  >
    計算 (Calculate)
  </button>

  {#if result}
    <div class="border-t-2 border-slate-300 dark:border-slate-700 pt-6 mt-6 space-y-3 animate-in fade-in">
      <div class="bg-orange-50 dark:bg-orange-900/20 p-4 rounded-lg">
        <p class="text-sm text-slate-600 dark:text-slate-400">真風風向</p>
        <p class="text-3xl font-bold text-orange-700 dark:text-orange-400">
          {result.trueWindDirection.toFixed(1)}°
        </p>
      </div>

      <div class="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
        <p class="text-sm text-slate-600 dark:text-slate-400">真風風速</p>
        <p class="text-3xl font-bold text-red-700 dark:text-red-400">
          {result.trueWindSpeed.toFixed(1)} kt
        </p>
      </div>

      <div class="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg">
        <p class="text-sm text-slate-600 dark:text-slate-400">相対方位</p>
        <p class="text-2xl font-bold text-yellow-700 dark:text-yellow-400">
          {result.relativeDirection.toFixed(1)}°
        </p>
      </div>
    </div>
  {/if}
</div>
