// src/lib/components/shared/PositionInput.svelte
<script lang="ts">
  import DMSInput from './DMSInput.svelte';
  import type { DMSValue } from '$lib/types/navigation';

  let { lat = $bindable(), lon = $bindable(), latLabel = '緯度 (Lat)', lonLabel = '経度 (Lon)' }: {
    lat: DMSValue;
    lon: DMSValue;
    latLabel?: string;
    lonLabel?: string;
  } = $props();
</script>

<div class="grid grid-cols-2 gap-4">
  <DMSInput label={latLabel} bind:value={lat} showSign signType="NS" />
  <DMSInput label={lonLabel} bind:value={lon} showSign signType="EW" />
</div>

// src/components/shared/PositionInput.tsx
import { DMSInput } from './DMSInput';
import type { DMSValue } from '../../types/navigation';

interface PositionInputProps {
  lat: DMSValue;
  lon: DMSValue;
  onChangeLat: (v: DMSValue) => void;
  onChangeLon: (v: DMSValue) => void;
  latLabel?: string;
  lonLabel?: string;
}

export const PositionInput = ({
  lat, lon, onChangeLat, onChangeLon,
  latLabel = '緯度 (Lat)', lonLabel = '経度 (Lon)',
}: PositionInputProps) => (
  <div className="grid grid-cols-2 gap-4">
    <DMSInput label={latLabel} value={lat} onChange={onChangeLat} showSign signType="NS" />
    <DMSInput label={lonLabel} value={lon} onChange={onChangeLon} showSign signType="EW" />
  </div>
);
