// src/components/layout/MobileHeader.tsx
import { Anchor, Sun, Moon, Menu, X } from 'lucide-react';

interface MobileHeaderProps {
  isMenuOpen: boolean;
  onToggleMenu: () => void;
  theme: 'light' | 'dark';
  onToggleTheme: () => void;
}

export const MobileHeader = ({ isMenuOpen, onToggleMenu, theme, onToggleTheme }: MobileHeaderProps) => (
  <div className="lg:hidden bg-white dark:bg-slate-900 p-4 shadow-sm flex items-center justify-between z-20 border-b border-slate-200 dark:border-slate-800 flex-shrink-0 transition-colors">
    <div className="flex items-center gap-2 font-bold text-slate-800 dark:text-white">
      <Anchor className="text-blue-700 dark:text-blue-500" size={20} />
      航法計算アプリ
    </div>
    <div className="flex items-center gap-2">
      <button
        onClick={onToggleTheme}
        className="p-2 text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors"
      >
        {theme === 'light' ? <Moon size={20} /> : <Sun size={20} />}
      </button>
      <button onClick={onToggleMenu} className="p-2 text-slate-600 dark:text-slate-400">
        {isMenuOpen ? <X size={24} /> : <Menu size={24} />}
      </button>
    </div>
  </div>
);

// src/lib/components/layout/MobileHeader.svelte
<script lang="ts">
  import { Anchor, Menu, X, Sun, Moon } from 'lucide-svelte';

  let { isMenuOpen, onToggleMenu, theme, onToggleTheme }: {
    isMenuOpen: boolean;
    onToggleMenu: () => void;
    theme: 'light' | 'dark';
    onToggleTheme: () => void;
  } = $props();
</script>

<header class="lg:hidden flex items-center justify-between p-4 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 shadow-sm z-50 transition-colors">
  <button onclick={onToggleMenu} class="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
    {#if isMenuOpen}
      <X size={24} class="text-slate-700 dark:text-slate-300" />
    {:else}
      <Menu size={24} class="text-slate-700 dark:text-slate-300" />
    {/if}
  </button>
  <h1 class="text-lg font-bold flex items-center gap-2 text-slate-800 dark:text-white">
    <Anchor class="text-blue-600 dark:text-blue-400" size={20} /> 航法計算
  </h1>
  <button onclick={onToggleTheme} class="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
    {#if theme === 'dark'}
      <Sun size={20} class="text-slate-300" />
    {:else}
      <Moon size={20} class="text-slate-700" />
    {/if}
  </button>
</header>
